### ISSUE TITLE
`dmTraitCollectionDidChange(_ previousTraitCollection: DMTraitCollection?)` not called

### ISSUE THREAD

**Issue by lifution** [microsoft/FluentDarkModeKit#104]
**iOS 13 and newer**, method `dmTraitCollectionDidChange(_ previousTraitCollection: DMTraitCollection?)` not called after `overrideTraitCollection` updated.
This problem appeared in `UIImageView` and `UILabel`.
FluentDarkModeKit version: 1.0.3

**Comment by levinli303** [comment]
This is expected. The following classes are known to not call UIView's `traitCollectionDidChange` thus `dmTraitCollectionDidChange` cannot be bridged.

UIView subclasses: UIImageView, UILabel, UIDatePicker, UIPickerView
UIViewController subclass: UISplitViewController

My suggestion to fix it would be either:
1. Avoid subclassing these classes, but create a container view for the classes to handle `dmTraitCollectionDidChange`
2. Override `traitCollectionDidChange` and apply the same logic on iOS 13

**Comment by lifution** [comment]
@levinli303 Get it, thanks.
