### ISSUE TITLE
Memory 

### ISSUE THREAD

**Issue by aasdsjk** [microsoft/FluentDarkModeKit#105]
When I use like this，everytime i went into secondController, the app memory has grow and will not release :

`#import <FluentDarkModeKit/UIImage+DarkModeKit.h>
@interface SecondViewController ()
@property (nonatomic, strong) UIImageView *imageV;
@end

@implementation SecondViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    self.view.backgroundColor = [UIColor whiteColor];
    UIImage *lightImage =  [UIImage imageNamed:@"ad_owner_header"];
    
    UIImage *darkImage = [[self class] image:lightImage byApplyingAlpha:0.5];
    
    UIImage *image = [UIImage dm_imageWithLightImage:lightImage darkImage:darkImage];
    
    self.imageV.image = image;
    [self.view addSubview:self.imageV];
}
+ (UIImage *)image:(UIImage *)image byApplyingAlpha:(CGFloat) alpha {
    
    UIGraphicsBeginImageContextWithOptions(image.size, NO, 0.0f);
    CGContextRef ctx = UIGraphicsGetCurrentContext();
    CGRect rect = CGRectMake(0, 0, image.size.width, image.size.height);
    CGContextScaleCTM(ctx, 1, -1);
    CGContextTranslateCTM(ctx, 0, -rect.size.height);
    CGContextSetBlendMode(ctx, kCGBlendModeMultiply);
    CGContextSetAlpha(ctx, alpha);
    CGContextDrawImage(ctx, rect, image.CGImage);
    UIImage *newImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return newImage;
}

- (UIImageView *)imageV {
    if (!_imageV) {
        _imageV = [[UIImageView alloc] initWithFrame:CGRectMake(100, 200, 40, 20)];
    }
    return _imageV;
}`

**Comment by levinli303** [comment]
Hi there. can you create a sample project and upload it here for us to test, that would make it easier for us to locate the issue.

**Comment by aasdsjk** [comment]
here is the demo : [DYDemo2.zip](https://github.com/microsoft/FluentDarkModeKit/files/6498631/DYDemo2.zip)

**Comment by levinli303** [comment]
Please follow the guide https://github.com/microsoft/FluentDarkModeKit#get-started to correctly set up FluentDarkModeKit before using it. (It might not be working with Objective-C as of now since the setup functions are swift only, but should be easy to change it to Obj-C compatible).

I tested with your project without using FluentDarkModeKit,  replaced
```
UIImage *image = [UIImage dm_imageWithLightImage:lightImage darkImage:darkImage];
self.imageV.image = image;
```
with
```
self.imageV.image = lightImage;
```

there is still the memory growth that did not go down after going back to the first VC.

**Comment by aasdsjk** [comment]
if you use like this

`self.imageV.image = lightImage;`

the memory will grow up when went to second VC only on first time.

but, if use FluentDarkModeKit the memory will growth everytime when i go to second VC

**Comment by levinli303** [comment]
This is done without using FluentDarkModeKit but the memory is increasing.

https://user-images.githubusercontent.com/17924287/118607344-0a200400-b7eb-11eb-84b8-6aa4319b265e.mov

**Comment by aasdsjk** [comment]
oh, thank you, i find that the memory growth is bacause of  "UIGraphicsBeginImageContextWithOptions" .

**Comment by aasdsjk** [comment]
hi,  i tried like this, app memory are not  increasing:
`
UIImage *darkImage = [[self class] image:lightImage byApplyingAlpha:0.5];    
 // UIImage *image = [UIImage dm_imageWithLightImage:lightImage darkImage:darkImage];    
self.imageV.image = lightImage;
`

**Comment by aasdsjk** [comment]
i find that if i create image with UIGraphicsBeginImageContextWithOptions and register the image in to UIImageAsset, the memory  will never release.

**Comment by aasdsjk** [comment]
do you have any good advice?

**Comment by icodesign** [comment]
I think the question is out of the scope of current library. It's more of how your app manage images.

**Comment by levinli303** [comment]
it sounds like it is related to how UIKit manages image assets, so we cannot solve the issue where images are not released as a library.

But we do offer an option to not use image asset.

‘’’
configuration.useImageAsset = false
‘’’

Please see to the detail in get started section
