### ISSUE TITLE
Dark mode in HTML 

### ISSUE THREAD

**Issue by DylanFayant** [microsoft/FluentDarkModeKit#108]
Hello, 
Does this library contains the methods to parse a html/css string to support Dark Mode (used in Outlook to switch emails themes even if they are not fitted for dark mode) ? 
Thank you !

**Comment by MikeChongCan** [comment]
Hello, this library only supports native UI instead of those inside a web view.
We don't have the plan to open source our implementation for the web at this moment.

I'd suggest taking a look at the JavaScript community implementation, for example, https://www.npmjs.com/package/darkmode-js
