### ISSUE TITLE
'FluentDarkModeKit/FluentDarkModeKit-Swift.h' file not found

### ISSUE THREAD

**Issue by ChenZRCoding** [microsoft/FluentDarkModeKit#109]
This problem was encountered again with integration in OC projects

**Comment by levinli303** [comment]
are you using spm or cocoapods?

**Comment by ChenZRCoding** [comment]
> 你用的是spm还是cocoapods？

cocoapods

**Comment by levinli303** [comment]
I created a new project and it works fine for me.

The import statements should either be
```
@import FluentDarkModeKit;
@import FluentDarkModeKit.Swift;
```
or 
```
#import <FluentDarkModeKit/FluentDarkModeKit.h>
#import <FluentDarkModeKit/FluentDarkModeKit-Swift.h>
```

What os version and Xcode version are you using, what is the minimum deployment target you set? Can you share a sample project that does not work, (after running pod install).

**Comment by ChenZRCoding** [comment]
我已经解决了 在oc 项目中使用swift框架 需要在podfile中加入 use_frameworks! 但是现在出现个新问题 另外一个框架 pod install 之后会报错  ‘xxx’target has transitive dependencies that include statically linked binaries: 'xxxx' 问题

**Comment by levinli303** [comment]
this sounds irrelevant to FluentDarkModeKit, might be an incorrect configuration somewhere. Closing this issue.
