### ISSUE TITLE
Improve code documentation

### ISSUE THREAD

**Issue by icodesign** [microsoft/FluentDarkModeKit#13]

**Comment by imWildCat** [comment]
Shall we create issue templates as an interaction documentation? I found that we need information such as toolchain, library version for investigation, for example, in #87.

**Comment by levinli303** [comment]
that would be great @imWildCat I was finding it hard to gather info.

**Comment by icodesign** [comment]
Sounds good. Would you start with a minimal tempalte?

**Comment by imWildCat** [comment]
@icodesign Sure! Will do that in this week.
