### ISSUE TITLE
DMDynamicImageProxy may crash when proxying resizable Image

### ISSUE THREAD

**Issue by linlinyao1** [microsoft/FluentDarkModeKit#56]
`(UIImage *)resizableImageWithCapInsets:(UIEdgeInsets)capInsets resizingMode:(UIImageResizingMode)resizingMode `  returns _UIResizableImage, and when using DMDynamicImageProxy as _UIResizableImage in a UIButton, it tries to access to image's ivar which is not aligned with  DMDynamicImageProxy class

**Comment by linlinyao1** [comment]
change DMDynamicImageProxy from NSProxy to NSObject solve this problem

**Comment by levinli303** [comment]
@imWildCat @linlinyao1  do you still have sample codes that can reproduce it?

**Comment by levinli303** [comment]
Closing as there is no sample code provided.
