### ISSUE TITLE
Can not install 

### ISSUE THREAD

**Issue by hanjt** [microsoft/FluentDarkModeKit#61]
```
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'darkTest' do
    pod "FluentDarkModeKit"
end
```
Podfile like this. But when I input `pod install`, result like this

```test pod install
Analyzing dependencies
[!] Unable to find a specification for `FluentDarkModeKit`
```

**Comment by eyvallah** [comment]
Hello, the pod name has just been updated in 0.5.0, please try `pod install --repo-update`.

Also you might want to change `platform :ios, '10.0'` since we only support iOS 11+

**Comment by Natai** [comment]
Installing FluentDarkModeKit (0.5.1)

[!] Error installing FluentDarkModeKit
[!] /usr/local/bin/git clone https://github.com/microsoft/FluentDarkModeKit.git /var/folders/ln/fm_ny6xx64b01zxbyrh9p8w40000gq/T/d20200411-1655-1jbhuvu --template= --single-branch --depth 1 --branch 0.5.1

正克隆到 '/var/folders/ln/fm_ny6xx64b01zxbyrh9p8w40000gq/T/d20200411-1655-1jbhuvu'...
注意：正在检出 'd86190310e8fce7c67c8ea8bd906df723d99c6b8'。

您正处于分离头指针状态。您可以查看、做试验性的修改及提交，并且您可以通过另外
的检出分支操作丢弃在这个状态下所做的任何提交。

如果您想要通过创建分支来保留在此状态下所做的提交，您可以通过在检出命令添加
参数 -b 来实现（现在或稍后）。例如：

  git checkout -b <新分支名>

git-lfs filter-process: git-lfs: command not found
fatal: 远端意外挂断了
warning: 克隆成功，但是检出失败。
您可以通过 'git status' 检查哪些已被检出，然后使用命令
'git checkout -f HEAD' 重试

**Comment by imWildCat** [comment]
I've checked there's no issue with this pod:

```shell
➜  DemoAppDemo pod install
Analyzing dependencies
Downloading dependencies
Installing FluentDarkModeKit (0.5.1)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

Please:

- Install git-lfs on your machine: https://github.com/git-lfs/git-lfs/wiki/Installation
- Verify your internet connection
