### ISSUE TITLE
Will you support under iOS 11?

### ISSUE THREAD

**Issue by sunforcode** [microsoft/FluentDarkModeKit#62]
my app support iOS 9 and later, so I can't use this, will u support iOS9 in the future?

**Comment by icodesign** [comment]
Our app, Outlook Mobile for iOS, only supports iOS 12+ now and the library itself supports iOS 11+. There's no guarantee that the library will work prior iOS 11, but you can try yourself. I assume it will generally work out of box (you probably need fix some compile issues). Feel to fork and try it out.

**Comment by sunforcode** [comment]
> Our app, Outlook Mobile for iOS, only supports iOS 12+ now and the library itself supports iOS 11+. There's no guarantee that the library will work prior iOS 11, but you can try yourself. I assume it will generally work out of box (you probably need fix some compile issues). Feel to fork and try it out.

ok ty
