### ISSUE TITLE
The dark color didn't show when I switch to dark mode.

### ISSUE THREAD

**Issue by OysterSu** [microsoft/FluentDarkModeKit#63]
As title. Does anybody meet the same problem?

OS X: 10.15.3
Xcode: 11.4
FluentDarkModeKit: 0.5.1

**Comment by icodesign** [comment]
Is there any sample code or demo project we can look at?

**Comment by karanokk** [comment]
try DarkModeManager.setup()

**Comment by icodesign** [comment]
Close due to inactivity.
