### ISSUE TITLE
Supporting Multiple Color Schemes

### ISSUE THREAD

**Issue by TimOliver** [microsoft/FluentDarkModeKit#64]
G'day folks!

Congratulations on an absolutely brilliant library! I've been curious for a while about how easy building a third party theming system that integrates with UIKit would be, and it looks like this is the most elegant way out there.

One extra thing I was curious about was the concept of being able to have multiple color themes on top of light mode and dark. For example, Twitter for iOS offers both a dark blue, and a pure black theme, offering the user more choices for customisability, and apps like Tweetbot and Apollo for Reddit support upwards of 5 or 6 completely different color schemes.

I noticed there was [an issue for making the color API more flexible](https://github.com/microsoft/FluentDarkModeKit/issues/11) at one point. Is that sort of functionality something you're interested in adding?

If it isn't, is it something you'd be interested in receiving a PR for?

**Comment by icodesign** [comment]
Hi @TimOliver , thanks for bringing this out. I've reopened that issue. This is a great feature we'd like to add .That's probably a promising direction that we should go in.

**Comment by TimOliver** [comment]
Hi @icodesign! Fantastic! Thanks so much for that! :D
If there's anything I can do to help, please let me know. :)

**Comment by icodesign** [comment]
Hi @TimOliver ,

As our project will be dropping iOS 12 support soon, we also added a bridge for iOS 13 native API support in FluentDarkModeKit. We've decided not to support multiple color schemes for a better native API compatibility until iOS provides multiple color support in the future. So if you're interested in this feature request, I'd suggest you could fork and create your own. It should be pretty straightforward if you use the previous iOS 12 approach.

**Comment by TimOliver** [comment]
Hi @icodesign!

Ahh fair enough. That seems like the right direction to head in. No problems! I'll consider what to do from this point onwards.

Thanks for the heads-up! All the best of luck!
