### ISSUE TITLE
Error pod install

### ISSUE THREAD

**Issue by superbon** [microsoft/FluentDarkModeKit#66]
[!] Error installing FluentDarkModeKit
[!] /usr/local/bin/git clone https://github.com/microsoft/FluentDarkModeKit.git /var/folders/9y/1mstvkp95271pqp41608cdnr0000gn/T/d20200516-24535-rxl3np --template= --single-branch --depth 1 --branch 0.5.1

**Comment by imWildCat** [comment]
Hi @superbon, I cannot reproduce this issue.

Could you please add more information? Such as the system version, ruby version, pod version and Xcode version?

If you can post more logs, that would be very helpful.

**Comment by superbon** [comment]
Hi @imWildCat 

> Could you please add more information? Such as the version of:
> 
> * macOS - Catalina 10.15.4
> * ruby. - 2.7.1
> * pod -  1.9.1
> * Xcode - 11.4.1 

Here are the full error logs.

Analyzing dependencies
Downloading dependencies
Installing FluentDarkModeKit (0.5.1)

[!] Error installing FluentDarkModeKit
[!] /usr/local/bin/git clone https://github.com/microsoft/FluentDarkModeKit.git /var/folders/9y/1mstvkp95271pqp41608cdnr0000gn/T/d20200520-4948-1uvaud5 --template= --single-branch --depth 1 --branch 0.5.1

Cloning into '/var/folders/9y/1mstvkp95271pqp41608cdnr0000gn/T/d20200520-4948-1uvaud5'...
Note: switching to 'd86190310e8fce7c67c8ea8bd906df723d99c6b8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by imWildCat** [comment]
According to your logs,

> git-lfs filter-process: git-lfs: command not found

you need to install `git-lfs`: https://git-lfs.github.com/

**Comment by eyvallah** [comment]
Maybe we should mention it in README.md that git-lfs is required, I don't think CocoaPods require git-lfs to be installed.
