### ISSUE TITLE
Project does not build once added.

### ISSUE THREAD

**Issue by oswaldt** [microsoft/FluentDarkModeKit#72]
I get the following error when building my app. In the file DarkModeCore/UIColor+DarkModeKit.h
#import <FluentDarkModeKit/DMNamespace.h> is not found. 

<img width="986" alt="Screen Shot 2020-06-06 at 2 59 00 PM" src="https://user-images.githubusercontent.com/47340336/83952386-987fbd80-a806-11ea-8ba1-bdc8a1c092c4.png">

**Comment by karanokk** [comment]
#69 already fixed. new version not released yet
Add to SPM by using lastest commit ae1f137759a33fc397367fa4e951800145b579a7

**Comment by icodesign** [comment]
Thanks @karanokk. 

@oswaldt I've published a new release (0.5.2). Should be able to work now.
