### ISSUE TITLE
Does it support layer?

### ISSUE THREAD

**Issue by VineFiner** [microsoft/FluentDarkModeKit#74]
I use this
```
  view.layer.borderColor = UIColor (.dm, light color: .red, dark color: .green).cgColor
```
But there is no response.

**Comment by eyvallah** [comment]
No it does not. Neither does Apple's API.

To support dynamic color involving CGColor, you might want to manually set the color to your desired color in `dmTraitCollectionDidChange` of the view.

**Comment by VineFiner** [comment]
> No it does not. Neither does Apple's API.
> 
> To support dynamic color involving CGColor, you might want to manually set the color to your desired color in `dmTraitCollectionDidChange` of the view.

Okay thank you. Is this library just an official extension?

**Comment by eyvallah** [comment]
The library has its own implementation and is not dependent on Apple's mechanism. However, we are working to align the library's API to that of Apple's for easy integration/migration.

**Comment by icodesign** [comment]
As pointed in README:
> For more information on cases you should handle during layout, please refer to [Apple's documentation](https://developer.apple.com/documentation/xcode/supporting_dark_mode_in_your_interface#2993898).

you can choose any of the following layout methods.
![image](https://user-images.githubusercontent.com/1148601/84103466-ac653280-aa45-11ea-8b45-26552e3f1427.png)
