### ISSUE TITLE
How to use ？

### ISSUE THREAD

**Issue by xxxIxxxx** [microsoft/FluentDarkModeKit#83]
There is no change
> FluentDarkModeKit~> 0.5.2 | iOS14 | Xcode 12.0
```
1.Xcode  ->  New project

2.application didFinishLaunchingWithOptions  ->  DarkModeManager.setup()

3.ViewController  ->  view.backgroundColor = UIColor(.dm, light: .red, dark: .blue)
```
---
but your demo is good

**Comment by levinli303** [comment]
Hello here.

Can you please give a detail description of what the issue and the expected outcome is?

**Comment by xxxIxxxx** [comment]
切换深色模式没效果

我新建了一个工程，在 
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
// 调用了  
DarkModeManager.setup()
        return true
    }
```

然后在ViewController 进行背景色赋值  view.backgroundColor = UIColor(.dm, light: .red, dark: .blue)

在系统的控制中心 切换深色和浅色 背景色并没有变化。

但是下载的demo可以。。
中文应该可以吧  😅

**Comment by levinli303** [comment]
The latest release version (0.5.2) on CocoaPods, SPM, Carthage does not include system appearance change detection. Thus we do not have a "followSystem" theme. To do that, you have to observe this change yourself, and then apply the theme by calling 

```
DMTraitCollection.currrent = DMTraitCollection(userInterfaceStyle: .light/.dark)
```

We are now working on a release which will integrate system appearance change detection, see #80

**Comment by xxxIxxxx** [comment]
明白了 谢谢！
