### ISSUE TITLE
Namespace style

### ISSUE THREAD

**Issue by VineFiner** [microsoft/FluentDarkModeKit#90]
Sorry, this may not be a wrong.

r.swift uses `.rx` to distinguish namespaces

Why didn’t you use the same method, for compatibility with `Objective-C`?

**Comment by levinli303** [comment]
Hello, I'm not familiar with rx, can you elaborate on what you mean by distinguishing namespaces? Thanks!

**Comment by VineFiner** [comment]
```
import Foundation

struct MyNameSpace<Base> {
 private let base: Base
 init(base: Base) {
    self.base = base
 }
}

extension MyNameSpace {
    func hello() {
        print("hello")
    }
}
protocol NameSpcaceWrappable {
    associatedtype T
    // 
    var rx: T { get }
    // 
    static var rx: T.Type { get }
}

// 
extension NameSpcaceWrappable {
    var rx: MyNameSpace<Self> {
         return MyNameSpace<Self>(base: self)
     }

     static var rx: MyNameSpace<Self>.Type {
         return MyNameSpace<Self>.self
     }
}

extension String: NameSpcaceWrappable {
    
}
```

```
let space = String()
space.rx.hello()
```

**Comment by levinli303** [comment]
hmm, maybe an example related to this project would be better, I'm still trying to know what you are proposing here. Wrap a UIColor/UIImage?

**Comment by VineFiner** [comment]
> hmm, maybe an example related to this project would be better, I'm still trying to know what you are proposing here. Wrap a UIColor/UIImage?


Yes, I found a binary library.


https://github.com/Elenionl/EasyDarkMode


Is it better for swift?

```

import EasyDarkMode

imageView.image = UIImage.dm.image(name: "check_light", dark: "check_dark")

```

**Comment by levinli303** [comment]
Closing, we do not intend to make interface changes in the future. Objective-C compatibility has been added a few commits ago.
