### ISSUE TITLE
Version not released in CocoaPods

### ISSUE THREAD

**Issue by levinli303** [microsoft/FluentDarkModeKit#99]
@imWildCat @icodesign @li-bei  can one of you push the latest version to CocoaPods' repo? I do not have the permission to push.

**Comment by imWildCat** [comment]
Done: https://cocoapods.org/pods/FluentDarkModeKit

**Comment by imWildCat** [comment]
In the future, we can possibly leverage GH actions to distribute this framework to CocoaPods autoamtically: https://github.com/marketplace/actions/deploy-to-cocoapod-action
